function mdl=build_mdl_from_predictors(predictors,modelTbl)
% returns a cross-validated fitrsvm model
% predictors = predictors to include given what stage you're in
% modelTbl = data to include as generated by modelPrep

modelTblNames=modelTbl.Properties.VariableNames;

predictorTbl=modelTbl(:,ismember(modelTblNames,predictors));

mdl=fitrsvm(predictorTbl,modelTbl.scoresToPredict,'Leaveout','on','PredictorNames',predictorTbl.Properties.VariableNames);

end